apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: pythonapp
  namespace: aayush
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp 
    spec:
      containers:
      - name: python-app
        image: aayush0307/pythonmyapp:V.9
        ports:
        - containerPort: 5000
       
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: aayush
spec:
  selector:
    app: pythonapp 
  type: NodePort
  ports:
   - port: 5000
     targetPort: 5000
     nodePort: 31110
